# 1) Examen

In [1]:
import numpy as np

## 2) Crear un vector de ceros de tamaño 10

In [2]:
vector_ceros = np.zeros(10)
vector_ceros

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])



## 3) Crear un vector de ceros de tamaño 10 y el de la posicion 5 sea igual a 1


In [3]:
vector_ceros_y_uno = np.zeros(10)
vector_ceros_y_uno[5] = 1
vector_ceros_y_uno

array([0., 0., 0., 0., 0., 1., 0., 0., 0., 0.])

## 4) Cambiar el orden de un vector de 50 elementos, el de la posicion 1 es el de la 50 etc.

In [6]:
vector_cincuenta_elementos = np.arange(50)



[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49]




## 5) Crear una matriz de 3 x 3 con valores del cero al 8



In [7]:
matriz_cero_al_ocho = np.arange(9).reshape(3,3)
matriz_cero_al_ocho

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

## 6) Encontrar los indices que no sean cero en un arreglo

```python
import numpy as np
arreglo = [1,2,0,0,4,0]
```

In [10]:
arreglo = np.array([1,2,0,0,4,0])
arreglo2 = arreglo > 0
arreglo[arreglo2]

array([1, 2, 4])

## 7) Crear una matriz de identidad 3 x 3

In [11]:
matriz_identidad = np.zeros(9).reshape(3,3)
for i in range(len(matriz_identidad)):
    for j in range(len(matriz_identidad[0])):
        if i == j:
            matriz_identidad[i,j] = 1
matriz_identidad

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])



## 8) Crear una matriz 3 x 3 x 3 con valores randomicos

In [13]:
matriz_randomicos = np.random.rand(3,3,3)
matriz_randomicos

array([[[0.94965843, 0.5494202 , 0.62076896],
        [0.20435937, 0.91419271, 0.68768931],
        [0.71477154, 0.33905473, 0.00854847]],

       [[0.48099319, 0.53467026, 0.45202542],
        [0.65107421, 0.15248493, 0.59579722],
        [0.05523844, 0.12642363, 0.67015305]],

       [[0.72686229, 0.37323013, 0.37712861],
        [0.57519167, 0.27700566, 0.7755003 ],
        [0.6433086 , 0.08035336, 0.15875322]]])


## 9) Crear una matriz 10 x 10 y encontrar el mayor y el menor



In [17]:
matriz_diez_por_diez = np.random.rand(10,10)
matriz_diez_por_diez

array([[0.7544583 , 0.86803502, 0.64315932, 0.4481018 , 0.64662508,
        0.78732997, 0.04957496, 0.25829682, 0.411831  , 0.32994218],
       [0.92631177, 0.29565414, 0.24142409, 0.84331681, 0.06362607,
        0.33604295, 0.09148936, 0.43185054, 0.64407369, 0.55022704],
       [0.90287064, 0.68998294, 0.04303732, 0.97064423, 0.87195843,
        0.43443259, 0.04240189, 0.27295232, 0.11999545, 0.7634208 ],
       [0.48832817, 0.28768768, 0.09174566, 0.54268665, 0.36434868,
        0.28014947, 0.72969745, 0.1746999 , 0.80880377, 0.34618876],
       [0.04562577, 0.8416804 , 0.7087657 , 0.00800393, 0.94835909,
        0.16495449, 0.09030176, 0.80412736, 0.32561404, 0.76887046],
       [0.28194844, 0.10188594, 0.59813832, 0.39400206, 0.91826886,
        0.52686728, 0.07073758, 0.28284541, 0.45786479, 0.21264582],
       [0.52069815, 0.7299701 , 0.33533884, 0.00680338, 0.43732208,
        0.83348726, 0.84336802, 0.89981289, 0.22136719, 0.51395905],
       [0.6212878 , 0.16058598, 0.1676595

In [19]:
np.max(matriz_diez_por_diez)

0.9924181800329546

In [20]:
np.min(matriz_diez_por_diez)

0.006803377020342061

## 10) Sacar los colores RGB unicos en una imagen (cuales rgb existen ej: 0, 0, 0 - 255,255,255 -> 2 colores)

## 11) ¿Como crear una serie de una lista, diccionario o arreglo?

```python
import numpy as np
mylist = list('abcedfghijklmnopqrstuvwxyz')
myarr = np.arange(26)
mydict = dict(zip(mylist, myarr))
```

In [24]:
import pandas as pd
mylist = list('abcedfghijklmnopqrstuvwxyz')
myarr = np.arange(26)
mydict = dict(zip(mylist, myarr))
pd.Series((mylist,myarr,mydict))

0    [a, b, c, e, d, f, g, h, i, j, k, l, m, n, o, ...
1    [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13,...
2    {'a': 0, 'b': 1, 'c': 2, 'e': 3, 'd': 4, 'f': ...
dtype: object

## 12) ¿Como convertir el indice de una serie en una columna de un DataFrame?

```python
mylist = list('abcedfghijklmnopqrstuvwxyz')
myarr = np.arange(26)
mydict = dict(zip(mylist, myarr))
ser = pd.Series(mydict) 
# Transformar la serie en dataframe y hacer una columna indice
```

In [34]:
mylist = list('abcedfghijklmnopqrstuvwxyz')
myarr = np.arange(26)
mydict = dict(zip(mylist, myarr))
ser = pd.Series(mydict) 
df = pd.DataFrame(ser)
df['index'] = np.random.rand()
df

0     index
a   0  0.996684
b   1  0.996684
c   2  0.996684
e   3  0.996684
d   4  0.996684
f   5  0.996684
g   6  0.996684
h   7  0.996684
i   8  0.996684
j   9  0.996684
k  10  0.996684
l  11  0.996684
m  12  0.996684
n  13  0.996684
o  14  0.996684
p  15  0.996684
q  16  0.996684
r  17  0.996684
s  18  0.996684
t  19  0.996684
u  20  0.996684
v  21  0.996684
w  22  0.996684
x  23  0.996684
y  24  0.996684
z  25  0.996684

## 13) ¿Como combinar varias series para hacer un DataFrame?

```python
import numpy as np
ser1 = pd.Series(list('abcedfghijklmnopqrstuvwxyz'))
ser2 = pd.Series(np.arange(26))
```


In [57]:
import numpy as np
ser1 = pd.Series(list('abcedfghijklmnopqrstuvwxyz'))
ser2 = pd.Series(np.arange(26))
pd.DataFrame(dict(s1 = ser1, s2 = ser2))

s1  s2
0   a   0
1   b   1
2   c   2
3   e   3
4   d   4
5   f   5
6   g   6
7   h   7
8   i   8
9   j   9
10  k  10
11  l  11
12  m  12
13  n  13
14  o  14
15  p  15
16  q  16
17  r  17
18  s  18
19  t  19
20  u  20
21  v  21
22  w  22
23  x  23
24  y  24
25  z  25

## 14) ¿Como obtener los items que esten en una serie A y no en una serie B?

```python
ser1 = pd.Series([1, 2, 3, 4, 5])
ser2 = pd.Series([4, 5, 6, 7, 8])
```

In [63]:
ser1 = pd.Series([1, 2, 3, 4, 5])
ser2 = pd.Series([4, 5, 6, 7, 8])
con1 = set(ser1)
con2 = set(ser2)
con3 = con1 - con2
con3

{1, 2, 3}

## 15) ¿Como obtener los items que no son comunes en una serie A y serie B?

```python
ser1 = pd.Series([1, 2, 3, 4, 5])
ser2 = pd.Series([4, 5, 6, 7, 8])
```

In [79]:
ser1 = pd.Series([1, 2, 3, 4, 5])
ser2 = pd.Series([4, 5, 6, 7, 8])
ser3 = pd.concat([ser1,ser2])
con1 = set(ser1)
con2 = set(ser2)
con3 = con1 - con2
con4 = con2 - con1
con_final = con3|con4
con_final

{1, 2, 3, 6, 7, 8}

## 16) ¿Como obtener el numero de veces que se repite un valor en una serie?

```python
ser = pd.Series(np.take(list('abcdefgh'), np.random.randint(8, size=30)))
```

In [82]:
ser = pd.Series(np.take(list('abcdefgh'), np.random.randint(8, size=30)))
ser.value_counts()

c    7
h    5
g    4
e    4
a    3
b    3
f    2
d    2
dtype: int64

## 17) ¿Como mantener los 2 valores mas repetidos de una serie, y a los demas valores cambiarles por 0 ?

```python
np.random.RandomState(100)
ser = pd.Series(np.random.randint(1, 5, [12]))
```

In [111]:
np.random.RandomState(100)
ser = pd.Series(np.random.randint(1, 5, [12]))
ser2 = ser.value_counts()
print(ser2)
print(np.array(ser2))
ser2[:2]


3    6
1    4
4    1
2    1
dtype: int64
[6 4 1 1]


3    6
1    4
dtype: int64

## 18) ¿Como transformar una serie de un arreglo de numpy a un DataFrame con un `shape` definido?


```python
ser = pd.Series(np.random.randint(1, 10, 35))
shape(7,5)
```

In [124]:
ser = pd.Series(np.random.randint(1, 10, 35))
df = pd.DataFrame(ser)
df


0
0   4
1   8
2   2
3   1
4   8
5   6
6   5
7   1
8   3
9   2
10  1
11  2
12  2
13  6
14  4
15  3
16  9
17  5
18  3
19  2
20  5
21  5
22  3
23  8
24  1
25  9
26  9
27  2
28  4
29  8
30  9
31  2
32  9
33  5
34  5

## 19) ¿Obtener los valores de una serie conociendo la posicion por indice?


```python
ser = pd.Series(list('abcdefghijklmnopqrstuvwxyz'))
pos = [0, 4, 8, 14, 20]
# a e i o u
```

In [139]:
ser[pos]

0     a
4     e
8     i
14    o
20    u
dtype: object


## 20) ¿Como anadir series vertical u horizontalmente a un DataFrame?


```python
ser1 = pd.Series(range(5))
ser2 = pd.Series(list('abcde'))
```



In [138]:
ser1 = pd.Series(range(5))
ser2 = pd.Series(list('abcde'))
df = pd.DataFrame([])
df['numero'] = ser1
df['letra'] = ser2
df

numero letra
0       0     a
1       1     b
2       2     c
3       3     d
4       4     e

In [125]:
ser = pd.Series(list('abcdefghijklmnopqrstuvwxyz'))
pos = [0, 4, 8, 14, 20]
# a e i o u



## 22)¿Como importar solo columnas especificas de un archivo csv?

https://raw.githubusercontent.com/selva86/datasets/master/BostonHousing.csv.

In [134]:
CSV_PATH = "https://raw.githubusercontent.com/selva86/datasets/master/BostonHousing.csv"
import requests
import io
s=requests.get(CSV_PATH).content

In [136]:
columnas_lanzamiento = ['crim','zn']
data_frame_completo = pd.read_csv(io.StringIO(s.decode('utf-8')),
        index_col= 'crim',
        usecols = columnas_lanzamiento)
data_frame_completo

zn
crim          
0.00632   18.0
0.02731    0.0
0.02729    0.0
0.03237    0.0
0.06905    0.0
0.02985    0.0
0.08829   12.5
0.14455   12.5
0.21124   12.5
0.17004   12.5
0.22489   12.5
0.11747   12.5
0.09378   12.5
0.62976    0.0
0.63796    0.0
0.62739    0.0
1.05393    0.0
0.78420    0.0
0.80271    0.0
0.72580    0.0
1.25179    0.0
0.85204    0.0
1.23247    0.0
0.98843    0.0
0.75026    0.0
0.84054    0.0
0.67191    0.0
0.95577    0.0
0.77299    0.0
1.00245    0.0
...        ...
4.87141    0.0
15.02340   0.0
10.23300   0.0
14.33370   0.0
5.82401    0.0
5.70818    0.0
5.73116    0.0
2.81838    0.0
2.37857    0.0
3.67367    0.0
5.69175    0.0
4.83567    0.0
0.15086    0.0
0.18337    0.0
0.20746    0.0
0.10574    0.0
0.11132    0.0
0.17331    0.0
0.27957    0.0
0.17899    0.0
0.28960    0.0
0.26838    0.0
0.23912    0.0
0.17783    0.0
0.22438    0.0
0.06263    0.0
0.04527    0.0
0.06076    0.0
0.10959    0.0
0.04741    0.0

[506 rows x 1 columns]